// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waxianhteemluqdnnipc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndheGlhbmh0ZWVtbHVxZG5uaXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODg1MDIsImV4cCI6MjA1ODg2NDUwMn0.f4CK2RBjb76D_x1G5ShQUa8G5SSTZv2wkQyQTLQ5YcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);